export const places = [
	/*{
		id:'pod-akacja',
    	coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_akacja1.jpg', author : ''},],
		title: 'Pod akacją',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-aniolem-strozem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_aniolem_strozem1.webp', author : ''},],
		title: 'Pod Aniołem Stróżem',
		address: '<b>Adres:</b> Główna 29',
		description: '<b>Opis: </b>Orginał znajduje się w Muzeum Pienińskim',
		//symbol: '',
	},
	{
		id:'pod-aniolkiem',
		coords: [49.423419, 20.486438],
		img: [{src : 'img/tablica/zdj/pod_aniolkiem.jpg', author : ''},],
		title: 'Pod aniołkiem',
		address: '<b>Adres:</b> Główna 31',
		description: '<b>Opis: </b>',
		//symbol: '',
	},
	{
		id:'pod-basami',
		coords: [49.420609, 20.490922],
		img: [{src : 'img/tablica/zdj/pod_basami1.jpg', author : ''},],
		title: 'Pod basami',
		address: '<b>Adres:</b> Szalaya 110',
		description: '<b>Opis: </b>',
		//symbol: '',
	},
	{
		id:'pod-batorym',
		coords: [49.425506, 20.486935],
		img: [{src : 'img/tablica/zdj/pod_batorym.png', author : ''},],
		title: 'Pod Batorym',
		address: '<b>Adres:</b> Park Górny 13',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-beczka',
		coords: [49.42002, 20.496491],
		img: [{src : 'img/tablica/zdj/pod_beczka1.jpg', author : ''},],
		title: 'Pod beczką',
		address: '<b>Adres:</b> Szlachtowska 28',
		description: '<b>Opis: </b>Godło nadane w 2022',
		//symbol: 'img/symbol/beczka.svg',
	},
	/*{
		id:'pod-bialym-orlem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_bialym_orlem.jpg', author : ''},],
		title: 'Pod Białym Orłem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-bogurodzica',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_bogurodzica.jpg', author : ''},],
		title: 'Pod Bogurodzicą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-boza-opatrznoscia',
		coords: [49.427029, 20.473863],
		img: [{src : 'img/tablica/zdj/pod_boza_opatrznoscia1.jpg', author : ''},],
		title: 'Pod Bożą Opatrznością',
		address: '<b>Adres:</b> Główna 46',
		description: '<b>Opis: </b>',
		//symbol: '',
	},
	{
		id:'pod-bucikiem',
		coords: [49.424651, 20.463701],
		img: [{src : 'img/tablica/zdj/pod_bucikiem1.webp', author : ''},],
		title: 'Pod bucikiem',
		address: '<b>Adres:</b> Flisacka 25a',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: 'img/symbol/bucik.svg',
	},
	{
		id:'pod-bzem',
		coords: [49.427649, 20.469984],
		img: [{src : 'img/tablica/zdj/pod_bzem1.jpg', author : ''},],
		title: 'Pod Bzem',
		address: '<b>Adres:</b> Główna 94',
		description: '<b>Opis: </b>',
		//symbol: '',
	},
	{
		id:'pod-capkiem',
		coords: [49.423162, 20.486919],
		img: [{src : 'img/tablica/zdj/pod_capkiem1.jpg', author : ''},],
		title: 'Pod capkiem',
		address: '<b>Adres:</b> Główna 48',
		description: '<b>Opis: </b>',
		//symbol: 'img/symbol/capek.svg',
	},
	/*{
		id:'pod-czeremcha',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_czeremcha.jpg', author : ''},],
		title: 'Pod Czeremchą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>Godło nadane w  2022?',
		//symbol: '',
	},*/
	/*{
		id:'pod-debem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_debem.jpg', author : ''},],
		title: 'Pod dębem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-diablem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_diablem.jpg', author : ''},],
		title: 'Pod Diabłem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-doboszem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_doboszem.jpg', author : ''},],
		title: 'Pod Doboszem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-dziadkiem',
		coords: [49.423298, 20.48738],
		img: [{src : 'img/tablica/zdj/pod_dziadkiem1.png', author : ''},],
		title: 'Pod dziadkiem',
		address: '<b>Adres:</b> Szalaya 50',
		description: '<b>Opis: </b>...',
		//symbol: 'img/symbol/dziadek.svg',
	},
	{
		id:'pod-dzwonem',
		coords: [49.427056, 20.473211],
		img: [{src : 'img/tablica/zdj/pod_dzwonem.jpg', author : ''},],
		title: 'Pod dzwonem',
		address: '<b>Adres:</b> Główna 37',
		description: '<b>Opis: </b>...',
		//symbol: 'img/symbol/dzwon.svg',
	},
	/*{
		id:'pod-figura',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_figura.jpg', author : ''},],
		title: 'Pod figurą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-gackiem',
		coords: [49.426272, 20.476756],
		img: [{src : 'img/tablica/zdj/pod_gackiem2.jpg', author : ''},],
		title: 'Pod gackiem',
		address: '<b>Adres:</b> Główna 25',
		description:'<b>Opis: </b>Godło nadane w 2022r ',
		//symbol: 'img/symbol/gacek.svg',
	},
	/*{
		id:'pod-gaweda',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_gaweda.jpg', author : ''},],
		title: 'Pod gawędą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},*/
	/*{
		id:'pod-geslami',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_geslami.jpg', author : ''},],
		title: 'Pod gęślami',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{	
		id:'pod-golabkiem',
		coords: [49.421955, 20.485953],
		img: [{src : 'img/tablica/zdj/pod_golobkiem1.jpg', author : ''},],
		title: 'Pod gołąbkiem',
		address: '<b>Adres:</b> Zawodzie 12',
		description: '<b>Opis: </b>...',
		//symbol: 'img/symbol/gołąb.svg',
	},
	{
		id:'pod-goralem',
		coords: [49.42359, 20.485812],
		img: [{src : 'img/tablica/zdj/pod_goralem1.jpg', author : 'zdj. własne'},],
		title: 'Pod góralem',
		address: '<b>Adres:</b> Szalaya 27',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-goralka',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_geslka.jpg', author : ''},],
		title: 'Pod góralką',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-grajcarkiem',
		coords: [49.426485, 20.465965],
		img: [{src : 'img/tablica/zdj/pod_grajcarkiem.jpg', author : ''},],
		title: 'Pod Grajcarkiem',
		address: '<b>Adres:</b> Nad Grajcarkiem 14',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-gwiazda',
		coords: [49.424805, 20.483966],
		img: [{src : 'img/tablica/zdj/pod_gwizda1.jpg', author : ''},],
		title: 'Pod gwiazdą',
		address: '<b>Adres:</b> Szalaya 19',
		description: '<b>Opis: </b>...',
		//symbol: 'img/symbol/gwiazda.svg',
	},
	{
		id:'pod-hamernikiem',
		coords: [49.430466, 20.488638],
		img: [{src : 'img/tablica/zdj/pod_hamernikiem1.jpg', author : ''},],
		title: 'Pod hamernikiem',
		address: '<b>Adres:</b> Kowalczyk 3b',
		description: '<b>Opis: </b>Godło nadane w 2022',
		//symbol: 'img/symbol/hamernik.svg',
	},
	{
		id:'pod-hiszpanem',
		coords: [49.427347, 20.472779],
		img: [{src : 'img/tablica/zdj/pod_hiszpanem1.jpg', author : ''},],
		title: 'Pod hiszpanem',
		address: '<b>Adres:</b> Główna 62',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-huzarem',
		coords: [49.423, 20.48606],
		img: [{src : 'img/tablica/zdj/pod_huzarem1.png', author : ''},],
		title: 'Pod Huzarem',
		address: '<b>Adres:</b> Szalaya 38',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-jablkiem',
		coords: [49.422455, 20.488759],
		img: [{src : 'img/tablica/zdj/pod_jablkiem1.jpg', author : ''},],
		title: 'Pod jabłkiem',
		address: '<b>Adres:</b> Szalaya 75',
		description: '<b>Opis: </b>...',
		//symbol: 'img/symbol/jabłko.svg',
	},
	{
		id:'pod-jalowcem',
		coords: [49.424599, 20.483393],
		img: [{src : 'img/tablica/zdj/pod_jalowcem1.jpg', author : ''},],
		title: 'Pod jałowcem',
		address: '<b>Adres:</b> Szalaya 15',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-jarzebinka',
		coords: [49.423006, 20.486579],
		img: [{src : 'img/tablica/zdj/pod_jarzebinka1.jpg', author : 'zdj. własne'},],
		title: 'Pod jarzębinką',
		address: '<b>Adres:</b> Szalaya 41a',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-jeleniem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_jeleniem.jpg', author : ''},],
		title: 'Pod jeleniem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-jemiola',
		coords: [49.42854, 20.495899],
		img: [
			{src : 'img/tablica/zdj/pod_jemiola1.jpg', author : 'zdj. własne'}			
		],
		title: 'Pod jemiołą',
		address: '<b>Adres:</b> Św. Krzyża  49',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-kapliczka',
		coords: [49.424591, 20.499702],
		img: [{src : 'img/tablica/zdj/pod_kapliczka1.jpg', author : ''},],
		title: 'Pod kapliczką',
		address: '<b>Adres:</b> Sopotnicka 22c',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-klonem',
		coords: [49.424756, 20.487441],
		img: [{src : 'img/tablica/zdj/pod_klonem1.jpg', author : ''},],
		title: 'Pod klonem',
		address: '<b>Adres:</b> Park Górny 16',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kogutkiem',
		coords: [49.419802, 20.500657],
		img: [{src : 'img/tablica/zdj/pod_kogutkiem1.jpg', author : ''},],
		title: 'Pod kogutkiem',
		address: '<b>Adres:</b> Szlachtowska 68',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kolem',
		coords: [49.427184, 20.472474],
		img: [{src : 'img/tablica/zdj/pod_kolem1.jpg', author : ''},],
		title: 'Pod kołem',
		address: '<b>Adres:</b> Główna 45',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-konikiem',
		coords: [49.422873, 20.487953],
		img: [{src : 'img/tablica/zdj/pod_konikiem1.jpg', author : ''},],
		title: 'Pod konikiem',
		address: '<b>Adres:</b> Szalaya 55',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kosynierem',
		coords: [49.420747, 20.48984],
		img: [{src : 'img/tablica/zdj/pod_kosynierem1.jpg', author : ''},],
		title: 'Pod kosynierem',
		address: '<b>Adres:</b> Szalaya 96',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-kosciuszka',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_kosciuszka1.jpg', author : ''},],
		title: 'Pod Kościuszką',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-kotwica',
		coords: [49.423004, 20.487296],
		img: [{src : 'img/tablica/zdj/pod_kotwica1.jpg', author : 'zdj. własne'},],
		title: 'Pod kotwicą',
		address: '<b>Adres:</b> Szalaya 53',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kozakiem',
		coords: [49.422348, 20.488928],
		img: [{src : 'img/tablica/zdj/pod_kozakiem1.jpg', author : ''},],
		title: 'Pod kozakiem',
		address: '<b>Adres:</b> Szalaya 77',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-kozica',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_kozica1.jpg', author : ''},],
		title: 'Pod kozicą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-krakowiakiem',
		coords: [49.429906, 20.50032],
		img: [{src : 'img/tablica/zdj/pod_krakowiakiem1.jpg', author : 'zdj. własne'},],
		title: 'Pod krakowiakiem',
		address: '<b>Adres:</b> Sopotnicka 28',
		description: '<b>Opis: </b>Godło nadane za wygrany konkurs rzucania siekierą do celu w 2016 podczas rozpoczyna cykl uroczystości organizowanych z okazji Roku Szalayowskiego',
		//symbol: '',
	},
	/*{
		id:'pod-ksiezycem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_ksiezycem1.jpg', author : ''},],
		title: 'Pod księżycem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-kukucka',
		coords: [49.40747, 20.565529],
		img: [{src : 'img/tablica/zdj/pod_kukucka1.jpg', author : ''},],
		title: 'Pod kukucką',
		address: '<b>Adres:</b> Biała Woda 57',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	/*{
		id:'pod-lira',
		coords: [49.427336, 20.47281],
		img: [{src : 'img/tablica/zdj/pod_lira1.jpg', author : ''},],
		title: 'Pod lirą',
		address: '<b>Adres:</b> Główna 62',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-lisem',
		coords: [49.422877, 20.488168],
		img: [{src : 'img/tablica/zdj/pod_lisem1.jpg', author : ''},],
		title: 'Pod lisem',
		address: '<b>Adres:</b> Szalaya 62',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-lukiem',
		coords: [49.424663, 20.483179],
		img: [{src : 'img/tablica/zdj/pod_lukiem1.jpg', author : ''},],
		title: 'Pod łukiem',
		address: '<b>Adres:</b> Szalaya 13',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-makiem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_makiem.jpg', author : ''},],
		title: 'Pod makiem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-matka-boska',
		coords: [49.427002, 20.474226],
		img: [{src : 'img/tablica/zdj/pod_matka_boska.jpg', author : ''},],
		title: 'Pod Matką Boską',
		address: '<b>Adres:</b> Główna 38',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-matrona',
		coords: [49.420638, 20.489704],
		img: [{src : 'img/tablica/zdj/pod_matrona1.jpg', author : ''},],
		title: 'Pod matroną',
		address: '<b>Adres:</b> Szalaya 96',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-mickiewiczem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_mickiewiczem.jpg', author : ''},],
		title: 'Pod Mickiewiczem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-modrzejewska',
		coords: [49.425419, 20.488147],
		img: [{src : 'img/tablica/zdj/pod_modrzejewska1.jpg', author : ''},],
		title: 'Pod Modrzejewską',
		address: '<b>Adres:</b> Park Górny 7',
		description: '<b>Opis: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-niedzwiedziem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_niedzwiedziem.jpg', author : ''},],
		title: 'Pod niedźwiedziem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-owocami',
		coords: [49.427448, 20.471997],
		img: [{src : 'img/tablica/zdj/pod_owocami1.jpg', author : ''},],
		title: 'Pod owocami',
		address: '<b>Adres:</b> Główna 70',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-palenica',
		coords: [49.424614, 20.482802],
		img: [{src : 'img/tablica/zdj/pod_palenica1.jpg', author : ''},],
		title: 'Pod Palenicą',
		address: '<b>Adres:</b> Szalaya 11 ?',
		description: '<b>Opis: </b>Godło nadane w 2022',
		//symbol: '',
	},
	{
		id:'pod-pielgrzymem',
		coords: [49.42715, 20.472689],
		img: [{src : 'img/tablica/zdj/pod_pielgrzymem1.jpg', author : ''},],
		title: 'Pod pielgrzymem',
		address: '<b>Adres:</b> Główna 43',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-pieskiem',
		coords: [49.423653, 20.486731],
		img: [{src : 'img/tablica/zdj/pod_pieskiem1.jpg', author : ''},],
		title: 'Pod pieskiem',
		address: '<b>Adres:</b> Szalaya 44a',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-polska-korona',
		coords: [49.42279, 20.488796],
		img: [{src : 'img/tablica/zdj/pod_polska_korona1.jpg', author : ''},],
		title: 'Pod polską koroną',
		address: '<b>Adres:</b> Szalaya 69',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-pomarancza',
		coords: [49.42724, 20.484642],
		img: [{src : 'img/tablica/zdj/pod_pomarancza1.jpg', author : ''},],
		title: 'Pod pomarańczą',
		address: '<b>Adres:</b> Zdrojowa 19',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-prusem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_prusem.jpg', author : ''},],
		title: 'Pod Prusem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-rakiem',
		coords: [49.423246, 20.486753],
		img: [{src : 'img/tablica/zdj/pod_rakiem1.jpg', author : 'zdj. własne'},],
		title: 'Pod rakiem',
		address: '<b>Adres:</b> Szalaya 43',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-roza',
		coords: [49.423444, 20.48661],
		img: [{src : 'img/tablica/zdj/pod_roza1.jpg', author : ''},],
		title: 'Pod różą',
		address: '<b>Adres:</b> Szalaya 39',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-ryba',
		coords: [49.423, 20.486468],
		img: [{src : 'img/tablica/zdj/pod_ryba1.jpg', author : ''},],
		title: 'Pod rybą',
		address: '<b>Adres:</b> Szalaya 41',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sarenka',
		coords: [49.425678, 20.462774],
		img: [{src : 'img/tablica/zdj/pod_sarenka1.jpg', author : ''},],
		title: 'Pod sarenką',
		address: '<b>Adres:</b> Główna 162',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-sercem',
		coords: [49.42719, 20.473456],
		img: [{src : 'img/tablica/zdj/pod_sercem1.jpg', author : ''},],
		title: 'Pod sercem',
		address: '<b>Adres:</b> Główna 56',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-siekierkami',
		coords: [49.425743, 20.484381],
		img: [{src : 'img/tablica/zdj/pod_siekierkami1.jpg', author : ''},],
		title: 'Pod siekierkami',
		address: '<b>Adres:</b> Zdrojowa 12',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sienkiewiczem',
		coords: [49.426514, 20.481012],
		img: [{src : 'img/tablica/zdj/pod_sienkiewiczem.jpg', author : ''},],
		title: 'Pod Sienkiewiczem',
		address: '<b>Adres:</b> Główna 12',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-skrzypkiem',
		coords: [49.428761, 20.466021],
		img: [{src : 'img/tablica/zdj/pod_skrzypkiem1.jpg', author : ''},],
		title: 'Pod skrzypkiem',
		address: '<b>Adres:</b> Pod Sadami 9b',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-sloncem',
		coords: [49.424639, 20.483683],
		img: [{src : 'img/tablica/zdj/pod_sloncem1.jpg', author : 'zdj. własne'},],
		title: 'Pod słońcem',
		address: '<b>Adres:</b> Szalaya 17',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-slowackim',
		coords: [49.427909, 20.474298],
		img: [{src : 'img/tablica/zdj/pod_slowackim1.jpg', author : ''},],
		title: 'Pod Słowackim',
		address: '<b>Adres:</b> Aleja parkowa 7',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-slowikiem',
		coords: [49.427088, 20.473007],
		img: [{src : 'img/tablica/zdj/pod_slowikiem1.jpg', author : ''},],
		title: 'Pod słowikiem',
		address: '<b>Adres:</b> Główna 39',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sokolem',
		coords: [49.427408, 20.472248],
		img: [{src : 'img/tablica/zdj/pod_sokolem1.jpg', author : ''},],
		title: 'Pod sokołem',
		address: '<b>Adres:</b> Główna 68',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-sosnami',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_sosnami.jpg', author : ''},],
		title: 'Pod sosnami',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},*/
	{
		id:'pod-sowa',
		coords: [49.427582, 20.479576],
		img: [{src : 'img/tablica/zdj/pod_sowa1.jpg', author : ''},],
		title: 'Pod sową',
		address: '<b>Adres:</b> Park Dolny 16',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-srebrnym-orlem',
		coords: [49.424368, 20.48323],
		img: [{src : 'img/tablica/zdj/pod_srebrnym_orlem1.jpg', author : ''},],
		title: 'Pod srebrnym orłem',
		address: '<b>Adres:</b> Szalaya 14',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sroka',
		coords: [49.427219, 20.473138],
		img: [{src : 'img/tablica/zdj/pod_sroka1.jpg', author : ''},],
		title: 'Pod sroką',
		address: '<b>Adres:</b> Główna 58',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-strzelba',
		coords: [49.422681, 20.488498],
		img: [{src : 'img/tablica/zdj/pod_strzelba1.jpg', author : ''},],
		title: 'Pod strzelbą',
		address: '<b>Adres:</b> Szalaya 73',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-strzelcem',
		coords: [49.423361, 20.486178],
		img: [{src : 'img/tablica/zdj/pod_strzelcem1.jpg', author : ''},],
		title: 'Pod strzelcem',
		address: '<b>Adres:</b> Szalaya 30',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-szabla',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_szabla.jpg', author : ''},],
		title: 'Pod szablą',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-sw-jozefem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_sw_jozefem.jpg', author : ''},],
		title: 'Pod św. Józefem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-sw-teresa',
		coords: [49.42295, 20.486195],
		img: [{src : 'img/tablica/zdj/pod_sw_teresa.jpg', author : ''},],
		title: 'Pod św. Teresą',
		address: '<b>Adres:</b> Szalaya 38',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-swierkami',
		coords: [49.426375, 20.452098],
		img: [{src : 'img/tablica/zdj/pod_swierkami1.jpg', author : ''},],
		title: 'Pod świerkami',
		address: '<b>Adres:</b> Główna 212',
		description: '<b>Opis: </b>Godło nadane w 2022r.',
		//symbol: '',
	},
	{
		id:'pod-topola',
		coords: [49.427379, 20.472524],
		img: [{src : 'img/tablica/zdj/pod_topola1.jpg', author : ''},],
		title: 'Pod topolą',
		address: '<b>Adres:</b> Główna 66',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-trzema-koronami',
		coords: [49.427287, 20.471398],
		img: [{src : 'img/tablica/zdj/pod_trzema_koronami1.jpg', author : ''},],
		title: 'Pod trzema koronami',
		address: '<b>Adres:</b> Główna 59',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-trzema-liliami',
		coords: [49.427357,20.472679],
		img:{ [src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod trzema liliami',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-trzema-rozami',
		coords: [49.42517, 20.482248],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod trzema różami',
		address: '<b>Adres:</b> Główna 1',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-turkiem',
		coords: [49.427357,20.472679],
		img:[{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod turkiem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-tygrysem',
		coords: [49.427474, 20.471408],
		img: [{src : 'img/tablica/zdj/pod_tygrysem1.jpg', author : ''},],
		title: 'Pod tygrysem',
		address: '<b>Adres:</b> Główna 78',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-ulanem',
		coords: [49.422141, 20.488935],
		img: [{src : 'img/tablica/zdj/pod_ulanem1.jpg', author : ''},],
		title: 'Pod ułanem',
		address: '<b>Adres:</b> Szalaya 81',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-waga',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod wagą,
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-wegierska-korona',
		coords: [49.42586, 20.481793],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod węgierską koroną',
		address: '<b>Adres:</b>  Główna 6',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wegrzynem',
		coords: [49.422507, 20.488168],
		img: [{src : 'img/tablica/zdj/pod_wegrzynem1.jpg', author : 'zdj. własne'},],
		title: 'Pod węgrzynem',
		address: '<b>Adres:</b> Szalaya 72',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wezem',
		coords: [49.42321, 20.483915],
		img: [{src : 'img/tablica/zdj/pod_wezem1.jpg', author : ''},],
		title: 'Pod wężem',
		address: '<b>Adres:</b> Zawodzie 17',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wiencem',
		coords: [49.422597, 20.489099],
		img: [{src : 'img/tablica/zdj/pod_wiencem1.jpg', author : ''},],
		title: 'Pod wieńcem',
		address: '<b>Adres:</b> Szalaya 70',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wietrznym-mlynem',
		coords: [49.427207, 20.472332],
		img: [{src : 'img/tablica/zdj/pod_wietrznym_mlynem1.jpg', author : ''},],
		title: 'Pod wietrznym młynem',
		address: '<b>Adres:</b> Główna 47',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wilkiem',
		coords: [49.422923, 20.488747],
		img: [{src : 'img/tablica/zdj/pod_wilkiem1.jpg', author : ''},],
		title: 'Pod wilkiem',
		address: '<b>Adres:</b> Szalaya 68',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-winogronem',
		coords: [49.42728, 20.471583],
		img: [{src : 'img/tablica/zdj/pod_winogronem1.jpg', author : ''},],
		title: 'Pod winogronem',
		address: '<b>Adres:</b> Główna 57',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wioslem',
		coords: [49.424102, 20.487836],
		img: [{src : 'img/tablica/zdj/pod_wioslem1.jpg', author : ''},],
		title: 'Pod wiosłem',
		address: '<b>Adres:</b> Park Górny 17a',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wodospadem',
		coords: [49.430775, 20.500279],
		img: [{src : 'img/tablica/zdj/pod_wodospadem1.jpg', author : 'zdj. własne'},],
		title: 'Pod wodospadem',
		address: '<b>Adres:</b> Sopotnicka 35a',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	{
		id:'pod-wykrotem',
		coords: [49.427732, 20.46863],
		img: [{src : 'img/tablica/zdj/pod_wykrotem1.jpg', author : ''},],
		title: 'Pod wykrotem',
		address: '<b>Adres:</b> Skotnicka 6a',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zajacem',
		coords: [49.422761, 20.488024],
		img: [{src : 'img/tablica/zdj/pod_zajacem1.jpg', author : 'zdj. własne'},],
		title: 'Pod zającem',
		address: '<b>Adres:</b> Szalaya 61',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zawisza',
		coords: [49.427786, 20.480304],
		img: [{src : 'img/tablica/zdj/pod_zawisza1.jpg', author : ''},],
		title: 'Pod Zawiszą',
		address: '<b>Adres:</b> Park Dolny 12',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zbojem-pipikasem',
		coords: [49.428622, 20.473626],
		img: [{src : 'img/tablica/zdj/pod_zbojem_pipikasem1.jpg', author : ''},],
		title: 'Pod zbójem Pipikasem',
		address: '<b>Adres:</b> Zielona 1a ?',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},
	/*{
		id:'pod-zegarem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod zegarem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-zlotym-lwemm',
		coords: [49.422655, 20.487639],
		img: [{src : 'img/tablica/zdj/pod_zlotym_lwem1.jpg', author : 'zdj. własne'},],
		title: 'Pod złotym lwem',
		address: '<b>Adres:</b> Szalaya 56',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-zlotym-krzyzem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod złotym krzyżem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-',
		coords: [49.428830,20.473977],
		img: [{Prc : 'img/tablica/zdj/', author : ''},],
		title: 'Pod ',
		address: '<b>Adres:</b> Aleja Parkowa 13?',
		description: '<b>Opis: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-kajakiem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Pod kajakiem',
		address: '<b>Adres:</b> ',
		description: '<b>Opis: </b>Godło nadane w 2022r',
		//symbol: '',
	},*/
];
