export const places = [
	/*{
		id:'pod-akacja',
    	coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_akacja1.jpg', author : ''},],
		title: 'Under the acacia',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-aniolem-strozem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_aniolem_strozem1.webp', author : ''},],
		title: 'Under the Guardian Angel',
		address: '<b>Address:</b> Główna 29',
		description: '<b>Description: </b>The original is located in the Pieniny Museum.',
		//symbol: '',
	},
	{
		id:'pod-aniolkiem',
		coords: [49.423419, 20.486438],
		img: [{src : 'img/tablica/zdj/pod_aniolkiem.jpg', author : ''},],
		title: 'Under the angel',
		address: '<b>Address:</b> Główna 31',
		description: '<b>Description: </b>',
		//symbol: '',
	},
	{
		id:'pod-basami',
		coords: [49.420609, 20.490922],
		img: [{src : 'img/tablica/zdj/pod_basami1.jpg', author : ''},],
		title: 'Under the bass',
		address: '<b>Address:</b> Szalaya 110',
		description: '<b>Description: </b>',
		//symbol: '',
	},
	{
		id:'pod-batorym',
		coords: [49.425506, 20.486935],
		img: [{src : 'img/tablica/zdj/pod_batorym.png', author : ''},],
		title: 'Under Batory',
		address: '<b>Address:</b> Park Górny 13',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-beczka',
		coords: [49.42002, 20.496491],
		img: [{src : 'img/tablica/zdj/pod_beczka1.jpg', author : ''},],
		title: 'Under the barrel',
		address: '<b>Address:</b> Szlachtowska 28',
		description: '<b>Description: </b>Awarded in 2022',
		//symbol: 'img/symbol/beczka.svg',
	},
	/*{
		id:'pod-bialym-orlem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_bialym_orlem.jpg', author : ''},],
		title: 'Under the White Eagle',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-bogurodzica',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_bogurodzica.jpg', author : ''},],
		title: 'Under the Mother of God',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-boza-opatrznoscia',
		coords: [49.427029, 20.473863],
		img: [{src : 'img/tablica/zdj/pod_boza_opatrznoscia1.jpg', author : ''},],
		title: 'Under the God\'s providence',
		address: '<b>Address:</b> Główna 46',
		description: '<b>Description: </b>',
		//symbol: '',
	},
	{
		id:'pod-bucikiem',
		coords: [49.424651, 20.463701],
		img: [{src : 'img/tablica/zdj/pod_bucikiem1.webp', author : ''},],
		title: 'Under the shoe',
		address: '<b>Address:</b> Flisacka 25a',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: 'img/symbol/bucik.svg',
	},
	{
		id:'pod-bzem',
		coords: [49.427649, 20.469984],
		img: [{src : 'img/tablica/zdj/pod_bzem1.jpg', author : ''},],
		title: 'Under the lilac',
		address: '<b>Address:</b> Główna 94',
		description: '<b>Description: </b>',
		//symbol: '',
	},
	{
		id:'pod-capkiem',
		coords: [49.423162, 20.486919],
		img: [{src : 'img/tablica/zdj/pod_capkiem1.jpg', author : ''},],
		title: 'Under the goat',
		address: '<b>Address:</b> Główna 48',
		description: '<b>Description: </b>',
		//symbol: 'img/symbol/capek.svg',
	},
	/*{
		id:'pod-czeremcha',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_czeremcha.jpg', author : ''},],
		title: 'Under Czeremcha',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>Awarded in  2022?',
		//symbol: '',
	},*/
	/*{
		id:'pod-debem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_debem.jpg', author : ''},],
		title: 'Under the oak',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-diablem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_diablem.jpg', author : ''},],
		title: 'Under the devil',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-doboszem',
		coords: [49.426782, 20.474926],
		img: [{src : 'img/tablica/zdj/pod_doboszem.jpg', author : ''},],
		title: 'Under the drummer (military)',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	{
		id:'pod-dziadkiem',
		coords: [49.423298, 20.48738],
		img: [{src : 'img/tablica/zdj/pod_dziadkiem1.png', author : ''},],
		title: 'Under the grandpa',
		address: '<b>Address:</b> Szalaya 50',
		description: '<b>Description: </b>...',
		//symbol: 'img/symbol/dziadek.svg',
	},
	{
		id:'pod-dzwonem',
		coords: [49.427056, 20.473211],
		img: [{src : 'img/tablica/zdj/pod_dzwonem.jpg', author : ''},],
		title: 'Under the bell',
		address: '<b>Address:</b> Główna 37',
		description: '<b>Description: </b>...',
		//symbol: 'img/symbol/dzwon.svg',
	},
	/*{
		id:'pod-figura',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_figura.jpg', author : ''},],
		title: 'Under the figure',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-gackiem',
		coords: [49.426272, 20.476756],
		img: [{src : 'img/tablica/zdj/pod_gackiem2.jpg', author : ''},],
		title: 'Under the bat',
		address: '<b>Address:</b> Główna 25',
		description:'<b>Description: </b>Tablica nadana w 2022r dla budynku Hotel Szczawnica Park ',
		//symbol: 'img/symbol/gacek.svg',
	},
	/*{
		id:'pod-gaweda',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_gaweda.jpg', author : ''},],
		title: 'Under the gawęda',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},*/
	/*{
		id:'pod-geslami',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_geslami.jpg', author : ''},],
		title: 'Under the gusle',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-golabkiem',
		coords: [49.421955, 20.485953],
		img: [{src : 'img/tablica/zdj/pod_golobkiem1.jpg', author : ''},],
		title: 'Under the dove',
		address: '<b>Address:</b> Zawodzie 12',
		description: '<b>Description: </b>...',
		//symbol: 'img/symbol/gołąb.svg',
	},
	{
		id:'pod-goralem',
		coords: [49.42359, 20.485812],
		img: [{src : 'img/tablica/zdj/pod_goralem1.jpg', author : ''},],
		title: 'Under the highlander (mal)',
		address: '<b>Address:</b> Szalaya 27',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-goralka',
		coords: [49.425678,20.462774],
		img: [{src : 'img/tablica/zdj/pod_geslka.jpg', author : ''},],
		title: 'Under the highlander (fem)',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-grajcarkiem',
		coords: [49.426485, 20.465965],
		img: [{src : 'img/tablica/zdj/pod_grajcarkiem.jpg', author : ''},],
		title: 'Under Grajcarek',
		address: '<b>Address:</b> Nad Grajcarkiem 14',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-gwiazda',
		coords: [49.424805, 20.483966],
		img: [{src : 'img/tablica/zdj/pod_gwizda1.jpg', author : ''},],
		title: 'Under the star',
		address: '<b>Address:</b> Szalaya 19',
		description: '<b>Description: </b>...',
		//symbol: 'img/symbol/gwiazda.svg',
	},
	{
		id:'pod-hamernikiem',
		coords: [49.430466, 20.488638],
		img: [{src : 'img/tablica/zdj/pod_hamernikiem1.jpg', author : ''},],
		title: 'Under the steelworker',
		address: '<b>Address:</b> Kowalczyk 3b',
		description: '<b>Description: </b>Awarded in 2022',
		//symbol: 'img/symbol/hamernik.svg',
	},
	{
		id:'pod-hiszpanem',
		coords: [49.427347, 20.472779],
		img: [{src : 'img/tablica/zdj/pod_hiszpanem1.jpg', author : ''},],
		title: 'Under the Spanish',
		address: '<b>Address:</b> Główna 62',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-huzarem',
		coords: [49.423, 20.48606],
		img: [{src : 'img/tablica/zdj/pod_huzarem1.png', author : ''},],
		title: 'Under the Hussar',
		address: '<b>Address:</b> Szalaya 38',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-jablkiem',
		coords: [49.422455, 20.488759],
		img: [{src : 'img/tablica/zdj/pod_jablkiem1.jpg', author : ''},],
		title: 'Under the apple',
		address: '<b>Address:</b> Szalaya 75',
		description: '<b>Description: </b>...',
		//symbol: 'img/symbol/jabłko.svg',
	},
	{
		id:'pod-jalowcem',
		coords: [49.424599, 20.483393],
		img: [{src : 'img/tablica/zdj/pod_jalowcem1.jpg', author : ''},],
		title: 'Under the juniper',
		address: '<b>Address:</b> Szalaya 15',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-jarzebinka',
		coords: [49.423006, 20.486579],
		img: [{src : 'img/tablica/zdj/pod_jarzebina1.jpg', author : ''},],
		title: 'Under the rowan',
		address: '<b>Address:</b> Szalaya 41a',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-jeleniem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_jeleniem.jpg', author : ''},],
		title: 'Under the deer',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-jemiola',
		coords: [49.42854, 20.495899],
		img: [
			{src : 'img/tablica/zdj/pod_jemiola1.jpg', author : 'own photo'}			
		],
		title: 'Under the mistletoe',
		address: '<b>Address:</b> Św. Krzyża  49',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-kapliczka',
		coords: [49.424591, 20.499702],
		img: [{src : 'img/tablica/zdj/pod_kapliczka1.jpg', author : ''},],
		title: 'Under the chapel',
		address: '<b>Address:</b> Sopotnicka 22c',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-klonem',
		coords: [49.424756, 20.487441],
		img: [{src : 'img/tablica/zdj/pod_klonem1.jpg', author : ''},],
		title: 'Under the mapple tree',
		address: '<b>Address:</b> Park Górny 16',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kogutkiem',
		coords: [49.419802, 20.500657],
		img: [{src : 'img/tablica/zdj/pod_kogutkiem1.jpg', author : ''},],
		title: 'Under the rooster',
		address: '<b>Address:</b> Szlachtowska 68',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kolem',
		coords: [49.427184, 20.472474],
		img: [{src : 'img/tablica/zdj/pod_kolem1.jpg', author : ''},],
		title: 'Under the wheel',
		address: '<b>Address:</b> Główna 45',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-konikiem',
		coords: [49.422873, 20.487953],
		img: [{src : 'img/tablica/zdj/pod_konikiem1.jpg', author : ''},],
		title: 'Under the horse',
		address: '<b>Address:</b> Szalaya 55',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kosynierem',
		coords: [49.420747, 20.48984],
		img: [{src : 'img/tablica/zdj/pod_kosynierem1.jpg', author : ''},],
		title: 'Under the Scythemen',
		address: '<b>Address:</b> Szalaya 96',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-kosciuszka',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_kosciuszka1.jpg', author : ''},],
		title: 'Under Kościuszko',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-kotwica',
		coords: [49.423004, 20.487296],
		img: [{src : 'img/tablica/zdj/pod_kotwica1.jpg', author : 'own photo'},],
		title: 'Under the anchor',
		address: '<b>Address:</b> Szalaya 53',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-kozakiem',
		coords: [49.422348, 20.488928],
		img: [{src : 'img/tablica/zdj/pod_kozakiem1.jpg', author : ''},],
		title: 'Under the Cossack',
		address: '<b>Address:</b> Szalaya 77',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-kozica',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_kozica1.jpg', author : ''},],
		title: 'Under the chamois',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-krakowiakiem',
		coords: [49.429906, 20.50032],
		img: [{src : 'img/tablica/zdj/pod_krakowiakiem1.jpg', author : ''},],
		title: 'Under the Krakowiak',
		address: '<b>Address:</b> Sopotnicka 28',
		description: '<b>Description: </b>The emblem awarded for winning the axe throwing competition at the target in 2016 during the inauguration of a series of celebrations organized on the occasion of the Szalay Year',
		//symbol: '',
	},
	/*{
		id:'pod-ksiezycem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_ksiezycem1.jpg', author : ''},],
		title: 'Under the moon',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-kukucka',
		coords: [49.40747, 20.565529],
		img: [{src : 'img/tablica/zdj/pod_kukucka1.jpg', author : ''},],
		title: 'Under the cuckoo',
		address: '<b>Address:</b> Biała Woda 57',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	/*{
		id:'pod-lira',
		coords: [49.427336, 20.47281],
		img: [{src : 'img/tablica/zdj/pod_lira1.jpg', author : ''},],
		title: 'Under the lyre',
		address: '<b>Address:</b> Główna 62',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-lisem',
		coords: [49.422877, 20.488168],
		img: [{src : 'img/tablica/zdj/pod_lisem1.jpg', author : ''},],
		title: 'Under the fox',
		address: '<b>Address:</b> Szalaya 62',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-lukiem',
		coords: [49.424663, 20.483179],
		img: [{src : 'img/tablica/zdj/pod_lukiem1.jpg', author : ''},],
		title: 'Under the bow',
		address: '<b>Address:</b> Szalaya 13',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-makiem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_makiem.jpg', author : ''},],
		title: 'Under the poppy',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-matka-boska',
		coords: [49.427002, 20.474226],
		img: [{src : 'img/tablica/zdj/pod_matka_boska.jpg', author : ''},],
		title: 'Under the Mother of God',
		address: '<b>Address:</b> Główna 38',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-matrona',
		coords: [49.420638, 20.489704],
		img: [{src : 'img/tablica/zdj/pod_matrona1.jpg', author : ''},],
		title: 'Under the matron',
		address: '<b>Address:</b> Szalaya 96',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-mickiewiczem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_mickiewiczem.jpg', author : ''},],
		title: 'Under Mickiewicz',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-modrzejewska',
		coords: [49.425419, 20.488147],
		img: [{src : 'img/tablica/zdj/pod_modrzejewska1.jpg', author : ''},],
		title: 'Under Modrzejewska',
		address: '<b>Address:</b> Park Górny 7',
		description: '<b>Description: </b>',
		//symbol: '',
	},*/
	/*{
		id:'pod-niedzwiedziem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_niedzwiedziem.jpg', author : ''},],
		title: 'Under the bear',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-owocami',
		coords: [49.427448, 20.471997],
		img: [{src : 'img/tablica/zdj/pod_owocami1.jpg', author : ''},],
		title: 'Under the fruits',
		address: '<b>Address:</b> Główna 70',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-palenica',
		coords: [49.424614, 20.482802],
		img: [{src : 'img/tablica/zdj/pod_palenica1.jpg', author : ''},],
		title: 'Under Palenica',
		address: '<b>Address:</b> Szalaya 11 ?',
		description: '<b>Description: </b>Awarded in 2022',
		//symbol: '',
	},
	{
		id:'pod-pielgrzymem',
		coords: [49.42715, 20.472689],
		img: [{src : 'img/tablica/zdj/pod_pielgrzymem1.jpg', author : ''},],
		title: 'Under the pilgrim',
		address: '<b>Address:</b> Główna 43',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-pieskiem',
		coords: [49.423653, 20.486731],
		img: [{src : 'img/tablica/zdj/pod_pieskiem1.jpg', author : ''},],
		title: 'Under the dog',
		address: '<b>Address:</b> Szalaya 44a',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-polska-korona',
		coords: [49.42279, 20.488796],
		img: [{src : 'img/tablica/zdj/pod_polska_korona1.jpg', author : ''},],
		title: 'Under the Polish crown',
		address: '<b>Address:</b> Szalaya 69',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-pomarancza',
		coords: [49.42724, 20.484642],
		img: [{src : 'img/tablica/zdj/pod_pomarancza1.jpg', author : ''},],
		title: 'Under the orange',
		address: '<b>Address:</b> Zdrojowa 19',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-prusem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_prusem.jpg', author : ''},],
		title: 'Under Prus',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-rakiem',
		coords: [49.423246, 20.486753],
		img: [{src : 'img/tablica/zdj/pod_rakiem1.jpg', author : 'own photo'},],
		title: 'Under the cancer',
		address: '<b>Address:</b> Szalaya 43',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-roza',
		coords: [49.423444, 20.48661],
		img: [{src : 'img/tablica/zdj/pod_roza1.jpg', author : ''},],
		title: 'Under the rose',
		address: '<b>Address:</b> Szalaya 39',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-ryba',
		coords: [49.423, 20.486468],
		img: [{src : 'img/tablica/zdj/pod_ryba1.jpg', author : ''},],
		title: 'Under the fish',
		address: '<b>Address:</b> Szalaya 41',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sarenka',
		coords: [49.425678, 20.462774],
		img: [{src : 'img/tablica/zdj/pod_sarenka1.jpg', author : ''},],
		title: 'Under the roe deer',
		address: '<b>Address:</b> Główna 162',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-sercem',
		coords: [49.42719, 20.473456],
		img: [{src : 'img/tablica/zdj/pod_sercem1.jpg', author : ''},],
		title: 'Under the heart',
		address: '<b>Address:</b> Główna 56',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-siekierkami',
		coords: [49.425743, 20.484381],
		img: [{src : 'img/tablica/zdj/pod_siekierkami1.jpg', author : ''},],
		title: 'Under the axes',
		address: '<b>Address:</b> Zdrojowa 12',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sienkiewiczem',
		coords: [49.426514, 20.481012],
		img: [{src : 'img/tablica/zdj/pod_sienkiewiczem.jpg', author : ''},],
		title: 'Under Sienkiewicz',
		address: '<b>Address:</b> Główna 12',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-skrzypkiem',
		coords: [49.428761, 20.466021],
		img: [{src : 'img/tablica/zdj/pod_skrzypkiem1.jpg', author : ''},],
		title: 'Under the violinist',
		address: '<b>Address:</b> Under the Sadami 9b',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-sloncem',
		coords: [49.424639, 20.483683],
		img: [{src : 'img/tablica/zdj/pod_sloncem1.jpg', author : ''},],
		title: 'Under the sun',
		address: '<b>Address:</b> Szalaya 17',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-slowackim',
		coords: [49.427909, 20.474298],
		img: [{src : 'img/tablica/zdj/pod_slowackim1.jpg', author : ''},],
		title: 'Under Słowacki',
		address: '<b>Address:</b> Aleja parkowa 7',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-slowikiem',
		coords: [49.427088, 20.473007],
		img: [{src : 'img/tablica/zdj/pod_slowikiem1.jpg', author : ''},],
		title: 'Under the nightingale',
		address: '<b>Address:</b> Główna 39',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sokolem',
		coords: [49.427408, 20.472248],
		img: [{src : 'img/tablica/zdj/pod_sokolem1.jpg', author : ''},],
		title: 'Under the falcon',
		address: '<b>Address:</b> Główna 68',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-sosnami',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_sosnami.jpg', author : ''},],
		title: 'Under the pines',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>Awarded in 2022',
		//symbol: '',
	},*/
	{
		id:'pod-sowa',
		coords: [49.427582, 20.479576],
		img: [{src : 'img/tablica/zdj/pod_sowa1.jpg', author : ''},],
		title: 'Under the owl',
		address: '<b>Address:</b> Park Dolny 16',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-srebrnym-orlem',
		coords: [49.424368, 20.48323],
		img: [{src : 'img/tablica/zdj/pod_srebrnym_orlem1.jpg', author : ''},],
		title: 'Under the silver eagle',
		address: '<b>Address:</b> Szalaya 14',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-sroka',
		coords: [49.427219, 20.473138],
		img: [{src : 'img/tablica/zdj/pod_sroka1.jpg', author : ''},],
		title: 'Under the magpie',
		address: '<b>Address:</b> Główna 58',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-strzelba',
		coords: [49.422681, 20.488498],
		img: [{src : 'img/tablica/zdj/pod_strzelba1.jpg', author : ''},],
		title: 'Under the blunderbuss',
		address: '<b>Address:</b> Szalaya 73',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-strzelcem',
		coords: [49.423361, 20.486178],
		img: [{src : 'img/tablica/zdj/pod_strzelcem1.jpg', author : ''},],
		title: 'Under the gunner',
		address: '<b>Address:</b> Szalaya 30',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-szabla',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_szabla.jpg', author : ''},],
		title: 'Under the sabre',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-sw-jozefem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/pod_sw_jozefem.jpg', author : ''},],
		title: 'Under St. Joseph',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-sw-teresa',
		coords: [49.42295, 20.486195],
		img: [{src : 'img/tablica/zdj/pod_sw_teresa.jpg', author : ''},],
		title: 'Under St. Teresa',
		address: '<b>Address:</b> Szalaya 38',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-swierkami',
		coords: [49.426375, 20.452098],
		img: [{src : 'img/tablica/zdj/pod_swierkami1.jpg', author : ''},],
		title: 'Under the spruces',
		address: '<b>Address:</b> Główna 212',
		description: '<b>Description: </b>Awarded in 2022r.',
		//symbol: '',
	},
	{
		id:'pod-topola',
		coords: [49.427379, 20.472524],
		img: [{src : 'img/tablica/zdj/pod_topola1.jpg', author : ''},],
		title: 'Under the poplar',
		address: '<b>Address:</b> Główna 66',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-trzema-koronami',
		coords: [49.427287, 20.471398],
		img: [{src : 'img/tablica/zdj/pod_trzema_koronami1.jpg', author : ''},],
		title: 'Under three crowns',
		address: '<b>Address:</b> Główna 59',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-trzema-liliami',
		coords: [49.427357,20.472679],
		img:{ [src : 'img/tablica/zdj/', author : ''},],
		title: 'Under three lilies',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-trzema-rozami',
		coords: [49.42517, 20.482248],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under three roses',
		address: '<b>Address:</b> Główna 1',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-turkiem',
		coords: [49.427357,20.472679],
		img:[{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the Turk',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-tygrysem',
		coords: [49.427474, 20.471408],
		img: [{src : 'img/tablica/zdj/pod_tygrysem1.jpg', author : ''},],
		title: 'Under the tiger',
		address: '<b>Address:</b> Główna 78',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-ulanem',
		coords: [49.422141, 20.488935],
		img: [{src : 'img/tablica/zdj/pod_ulanem1.jpg', author : ''},],
		title: 'Under the Uhlan (lancer)',
		address: '<b>Address:</b> Szalaya 81',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-waga',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the scales,
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-wegierska-korona',
		coords: [49.42586, 20.481793],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the Hungarian crown',
		address: '<b>Address:</b>  Główna 6',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wegrzynem',
		coords: [49.422507, 20.488168],
		img: [{src : 'img/tablica/zdj/pod_wegrzynem1.jpg', author : 'own photo'},],
		title: 'Under the Hungarian',
		address: '<b>Address:</b> Szalaya 72',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wezem',
		coords: [49.42321, 20.483915],
		img: [{src : 'img/tablica/zdj/pod_wezem1.jpg', author : ''},],
		title: 'Under the snake',
		address: '<b>Address:</b> Zawodzie 17',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wiencem',
		coords: [49.422597, 20.489099],
		img: [{src : 'img/tablica/zdj/pod_wiencem1.jpg', author : ''},],
		title: 'Under the wreath',
		address: '<b>Address:</b> Szalaya 70',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wietrznym-mlynem',
		coords: [49.427207, 20.472332],
		img: [{src : 'img/tablica/zdj/pod_wietrznym_mlynem1.jpg', author : ''},],
		title: 'Under the windmill',
		address: '<b>Address:</b> Główna 47',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wilkiem',
		coords: [49.422923, 20.488747],
		img: [{src : 'img/tablica/zdj/pod_wilkiem1.jpg', author : ''},],
		title: 'Under the wolf',
		address: '<b>Address:</b> Szalaya 68',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-winogronem',
		coords: [49.42728, 20.471583],
		img: [{src : 'img/tablica/zdj/pod_winogronem1.jpg', author : ''},],
		title: 'Under the grape',
		address: '<b>Address:</b> Główna 57',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wioslem',
		coords: [49.424102, 20.487836],
		img: [{src : 'img/tablica/zdj/pod_wioslem1.jpg', author : ''},],
		title: 'Under the oar',
		address: '<b>Address:</b> Park Górny 17a',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-wodospadem',
		coords: [49.430775, 20.500279],
		img: [{src : 'img/tablica/zdj/pod_wodospadem1.jpg', author : ''},],
		title: 'Under the waterfall',
		address: '<b>Address:</b> Sopotnicka 35a',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	{
		id:'pod-wykrotem',
		coords: [49.427732, 20.46863],
		img: [{src : 'img/tablica/zdj/pod_wykrotem1.jpg', author : ''},],
		title: 'Under the windthrow',
		address: '<b>Address:</b> Skotnicka 6a',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zajacem',
		coords: [49.422761, 20.488024],
		img: [{src : 'img/tablica/zdj/pod_zajacem1.jpg', author : 'own photo'},],
		title: 'Under the hare',
		address: '<b>Address:</b> Szalaya 61',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zawisza',
		coords: [49.427786, 20.480304],
		img: [{src : 'img/tablica/zdj/pod_zawisza1.jpg', author : ''},],
		title: 'Under the Zawisza',
		address: '<b>Address:</b> Park Dolny 12',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	{
		id:'pod-zbojem-pipikasem',
		coords: [49.428622, 20.473626],
		img: [{src : 'img/tablica/zdj/pod_zbojem_pipikasem1.jpg', author : ''},],
		title: 'Under the robber Pipikas',
		address: '<b>Address:</b> Zielona 1a ?',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},
	/*{
		id:'pod-zegarem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the clock',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	{
		id:'pod-zlotym-lwemm',
		coords: [49.422655, 20.487639],
		img: [{src : 'img/tablica/zdj/pod_zlotym_lwem1.jpg', author : ''},],
		title: 'Under the golden lion',
		address: '<b>Address:</b> Szalaya 56',
		description: '<b>Description: </b>...',
		//symbol: '',
	},
	/*{
		id:'pod-zlotym-krzyzem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the golden cross',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-',
		coords: [49.428830,20.473977],
		img: [{Prc : 'img/tablica/zdj/', author : ''},],
		title: 'Under the ',
		address: '<b>Address:</b> Aleja Parkowa 13?',
		description: '<b>Description: </b>...',
		//symbol: '',
	},*/
	/*{
		id:'pod-kajakiem',
		coords: [49.427357,20.472679],
		img: [{src : 'img/tablica/zdj/', author : ''},],
		title: 'Under the kayak',
		address: '<b>Address:</b> ',
		description: '<b>Description: </b>Awarded in 2022r',
		//symbol: '',
	},*/
];
